language: node_js
cache: yarn

git:
  depth: 1

node_js:
  - "node"
  - "8"
  - "6"
  - "4"

matrix:
  include:
    - script: npm pack
      after_success:
        - npm install -g @zeus-ci/cli
        - zeus upload -t "application/tar+npm" *.tgz

if: tag IS blank

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/0326e47c-d43f-11e7-9d52-0a580a280203/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
